# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e68c04390beebdbf3f749c64f54e944216d04c10006eeefde57cf0c3acac922ccccf8377c2c32573538a69602f8bc0f92819eea8754ab45fd9ec6f8a7ad20d

test:
  secret_key_base: bc72254f07a417fa8421efa5020b97d5886b972427967ee102f0f13da20652c640a0e89296716a2f0445417df873c9cee3890240914ff95f439146f501539b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
